# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define() do

# Could not dump table "sqlite_sequence" because of following StandardError
#   Unknown type '' for column 'name'

end
